# Generated by Django 4.2.30 on 2026-05-08 06:42

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Store',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('location', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Zone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('zone_type', models.CharField(choices=[('ENTRANCE', 'Entrance'), ('EXIT', 'Exit'), ('AISLE', 'Aisle'), ('CHECKOUT', 'Checkout')], max_length=20)),
                ('coordinates', models.JSONField(help_text='Polygon coordinates for the zone')),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='zones', to='analytics.store')),
            ],
        ),
        migrations.CreateModel(
            name='Camera',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('stream_url', models.CharField(max_length=500)),
                ('is_active', models.BooleanField(default=True)),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cameras', to='analytics.store')),
            ],
        ),
        migrations.CreateModel(
            name='AnalyticsEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('event_type', models.CharField(choices=[('ENTRY', 'Entry'), ('EXIT', 'Exit'), ('ZONE_ENTER', 'Zone Enter'), ('ZONE_EXIT', 'Zone Exit'), ('OCCUPANCY_UPDATE', 'Occupancy Update')], max_length=20)),
                ('object_id', models.CharField(help_text='Tracking ID from CV service', max_length=100)),
                ('metadata', models.JSONField(default=dict)),
                ('camera', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='analytics.camera')),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='analytics.store')),
                ('zone', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='analytics.zone')),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
    ]
